# This is a basic workflow to help you get started with Actions

name: Update Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '10 10 * * *'
    
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: (( RANDOM % 2 ))
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install xplanet and dateutil
      run: sudo apt-get -y install xplanet && pip3 install python-dateutil

    - name: Generate wallpaper
      run: python3 wallpaper.py
      
    - name: Show the generated files
      run: ls .seenfromspace/
    
    - name: GH Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: .seenfromspace # The folder the action should deploy.
